### ISSUE TITLE
Crashes with OGRE_THREAD_PROVIDER != 0

### ISSUE THREAD

**Issue by paroj** [OGRECave/ogitor#12]
in 3 out of 4 starts in resource loading/ preparation. Probably a race condition somewhere.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
#### System Information
- Ogre Version: 1.12-master
- Operating System / Platform: Windows 10 x64
- RenderSystem: Direct3D9 Rendering Subsystem

I tried to reproduce this issue, but I couldn't. I tried it with `OGRE_THREAD_PROVIDER=4` and tried both `OGRE_THREAD_SUPPORT=1` and `OGRE_THREAD_SUPPORT=3`. I also started it multiple times and loaded projects but everything worked as expected.

**Comment by paroj** [comment]
it does not crash for me either any more. Probably some Ogre or Ogitor change silently fixed it..
