### ISSUE TITLE
Enable C++11 and replace Boost threads and regex

### ISSUE THREAD

**Issue by kPYKx7Ddw4n1aIKZ** [OGRECave/ogitor#15]
This project could safely require C++11.
Furtermore one could replace Boost threads by C++11 threads.
C++11 should also be able to replace the Boost regex library, although I'm not entirely sure about that.
Maybe one could even remove the Boost dependency completely.

**Comment by paroj** [comment]
fixed by 58e2cca70872c9ce63c3f30684b171f0fbb54043
