### ISSUE TITLE
 error C2491: “OgreBites::ApplicationContextQt::staticMetaObject”:  dllimport static member is not allowed in moc_OgreApplicationContextQt.cpp

### ISSUE THREAD

**Issue by ronaldpan** [OGRECave/ogitor#30]
error C2491: “OgreBites::ApplicationContextQt::staticMetaObject”:  dllimport static member is not allowed in moc_OgreApplicationContextQt.cpp

**Comment by paroj** [comment]
duplicate of https://github.com/OGRECave/ogre/issues/1550
