### ISSUE TITLE
std::length_error in qtOgitor

### ISSUE THREAD

**Issue by ronaldpan** [OGRECave/ogitor#32]
struct OgreContext : public OgreBites::ApplicationContextQt
{
    OgreContext() : OgreBites::ApplicationContextQt("Ogitor") {} // here Microsoft C++ exception: std::length_error

QT5.14.12+VS2017+Windows 10 + OGRE 20200423

**Comment by paroj** [comment]
verify that both ogre and ogitor are built with the same exception flags e.g. /EHsc

**Comment by ronaldpan** [comment]
I checked all the flag /EHsc. They are Yes in both ogre and ogitor. The error still occure in Debug and Release.

**Comment by ronaldpan** [comment]
I changed to empty string. I still got the Error : std::length_error at memory location
OgreContext() : OgreBites::ApplicationContextQt() {}

**Comment by paroj** [comment]
likely a Debug/ Release build mismatch
