### ISSUE TITLE
does the ogitor support ogre 2.x ?

### ISSUE THREAD

**Issue by zhuhaipeng-byte** [OGRECave/ogitor#48]
I use ogre2.1, vs2019 to compile the ogitor, there are many cmake errors!!! when i use ogre1.13.6, there are also cmake error, **# class Ogre::Camera don't have LookAt , setPosition.. function**,
if it do not support ogre2.x, will you update ogitor project in the future to support ogre2.x ？ thanks a lot, have a good day for you

**Comment by paroj** [comment]
ogre 2.x is not supported.

To use ogre1, you must built it with OGRE_NODELESS_POSITIONING=ON.

**Comment by zhuhaipeng-byte** [comment]
ok, thanks for your reply. i will try to built with OGRE_NODELESS_POSITIONING=ON.
